apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: dev
  labels:
    app: order
data:
  DJANGO_SETTINGS_MODULE: "config.settings.prod"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "pgpool.dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order"
  POSTGRES_SSLMODE: "disable"
  CORS_ALLOW_ALL_ORIGINS: "TRUE"
  LOG_LEVEL: "INFO"
  ENV_NAME: "prod"
