{{- if .Values.currentEnvironment }}
{{- $env := .Values.currentEnvironment -}}
{{- $project := .Values.projectName -}}
{{- range $app := .Values.applications }}
{{- if or (not $.Values.onlyApp) (eq $.Values.onlyApp $app.name) }}
{{- $ctx := dict "env" $env "project" $project "app" $app "Values" $.Values "Template" $.Template }}
{{- $lbl := dict "app" $app "env" $env "project" $project }}
{{- $ns := printf "%s-%s-%s" $env $project $app.type }}
{{- if $app.envList }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $app.name }}
  namespace: {{ $ns }}
  labels:
    {{- include "mca.labels" $lbl | nindent 4 }}
data:
  {{- include "mca.configData" (dict "app" $app "ctx" $ctx) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
