apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Refresh_Interval  5
        Multiline         Off
        Parser            docker

    [FILTER]
        Name             parser
        Match            kube.*
        Key_Name         log
        Parser           json
        Reserve_Data     On
        Preserve_Key     On

    [OUTPUT]
        Name            azure
        Match           *
        Customer_ID     20bcc7fd-26e6-4bd4-8562-2b839db43cd5
        Shared_Key      DDF++4RSxsJZM1DVHbYPCSM/eRdcW5zj5rzuaUdIPP+MW51C6VqFOG7m43XPnW08WYHQYpInRK/sgm3z0VOW3A==
        Log_Type        KubernetesLogs

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name        plain_text
        Format      regex
        Regex       ^(?<log>.*)$