apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: dev
  labels:
    app: catalogue
data:
  PORT: "4000"
  NODE_ENV: "production"
  DB_HOST: "pgcat.dev.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "catalogue"
  DB_SSL: "true"
  PGSSLMODE: "disable"