apiVersion: v1
kind: Secret
metadata:
  name: catalogue-secret
  namespace: dev
  labels:
    app: catalogue
type: Opaque
stringData:
  DB_USER: formation
  DB_PASSWORD: test
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=1311ad53-6ac0-4946-bb2f-48c60120bbd9;IngestionEndpoint=https://francecentral-1.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/;ApplicationId=d9efc03e-0523-42cc-9e0e-1ea237ed1ba4"
