apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: dev
  labels:
    app: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
    - name: http
      port: 4000
      targetPort: 4000
