namespace: dev

image:
  repository: crformation.azurecr.io/ecommerce-front
  tag: "7.0"
  pullPolicy: Always

replicaCount: 2

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: 0

affinity:
  nodepool: apps

service:
  type: ClusterIP
  port: 80

probes:
  path: /
  startup:
    periodSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 15
    failureThreshold: 3
  readiness:
    periodSeconds: 5
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

configmap:
  CATALOG: "http://98.66.248.206/api/products"
  ORDERS: "http://98.66.248.206/api/orders"
  PAYMENT: "http://98.66.248.206/api/payments"
  AUTH_ENABLED: "false"

pdb:
  minAvailable: 1

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpu:
    averageUtilization: 70
  memory:
    averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      percent: 100
      periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      percent: 25
      periodSeconds: 60

vpa:
  updateMode: "Off"

ingress:
  enabled: true
  name: ecommerce-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  routes:
    - path: /api/products
      pathType: Prefix
      service:
        name: catalogue
        port: 4000
    - path: /api/orders
      pathType: Prefix
      service:
        name: order
        port: 8000
    - path: /api/payments
      pathType: Prefix
      service:
        name: payment
        port: 8082
    - path: /
      pathType: Prefix
      service:
        name: front
        port: 80
