apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: dev
type: Opaque
data:
  # echo -n 'your-password' | base64
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  REPLICATION_PASSWORD: YWRtaW4xMjM=
  BACKUP_PASSWORD: YWRtaW4xMjM=